##################################################
# file: BFExchangeService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/local/bin/wsdl2py BFExchangeService.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from BFExchangeService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding
import betfair_api

# Messages  
getAccountFundsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAccountFunds").pyclass

getAccountFundsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAccountFundsResponse").pyclass

cancelBetsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "cancelBets").pyclass

cancelBetsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "cancelBetsResponse").pyclass

cancelBetsByMarketIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "cancelBetsByMarket").pyclass

cancelBetsByMarketOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "cancelBetsByMarketResponse").pyclass

updateBetsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "updateBets").pyclass

updateBetsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "updateBetsResponse").pyclass

placeBetsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "placeBets").pyclass

placeBetsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "placeBetsResponse").pyclass

getMarketIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarket").pyclass

getMarketOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketResponse").pyclass

getMarketInfoIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketInfo").pyclass

getMarketInfoOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketInfoResponse").pyclass

getMarketPricesIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketPrices").pyclass

getMarketPricesOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketPricesResponse").pyclass

getCompleteMarketPricesCompressedIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCompleteMarketPricesCompressed").pyclass

getCompleteMarketPricesCompressedOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCompleteMarketPricesCompressedResponse").pyclass

getMarketTradedVolumeCompressedIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketTradedVolumeCompressed").pyclass

getMarketTradedVolumeCompressedOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketTradedVolumeCompressedResponse").pyclass

getMarketPricesCompressedIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketPricesCompressed").pyclass

getMarketPricesCompressedOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketPricesCompressedResponse").pyclass

getAllMarketsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAllMarkets").pyclass

getAllMarketsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAllMarketsResponse").pyclass

getInPlayMarketsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getInPlayMarkets").pyclass

getInPlayMarketsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getInPlayMarketsResponse").pyclass

getPrivateMarketsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getPrivateMarkets").pyclass

getPrivateMarketsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getPrivateMarketsResponse").pyclass

getCurrentBetsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCurrentBets").pyclass

getCurrentBetsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCurrentBetsResponse").pyclass

getCouponIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCoupon").pyclass

getCouponOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCouponResponse").pyclass

getCurrentBetsLiteIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCurrentBetsLite").pyclass

getCurrentBetsLiteOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getCurrentBetsLiteResponse").pyclass

getMUBetsIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMUBets").pyclass

getMUBetsOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMUBetsResponse").pyclass

getMUBetsLiteIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMUBetsLite").pyclass

getMUBetsLiteOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMUBetsLiteResponse").pyclass

getDetailAvailableMktDepthIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getDetailAvailableMktDepth").pyclass

getDetailAvailableMktDepthOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getDetailAvailableMktDepthResponse").pyclass

getMarketTradedVolumeIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketTradedVolume").pyclass

getMarketTradedVolumeOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketTradedVolumeResponse").pyclass

getBetHistoryIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetHistory").pyclass

getBetHistoryOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetHistoryResponse").pyclass

getAccountStatementIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAccountStatement").pyclass

getAccountStatementOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getAccountStatementResponse").pyclass

getMarketProfitAndLossIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketProfitAndLoss").pyclass

getMarketProfitAndLossOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getMarketProfitAndLossResponse").pyclass

getBetIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBet").pyclass

getBetOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetResponse").pyclass

getBetLiteIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetLite").pyclass

getBetLiteOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetLiteResponse").pyclass

getBetMatchesLiteIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetMatchesLite").pyclass

getBetMatchesLiteOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getBetMatchesLiteResponse").pyclass

getSilksIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getSilks").pyclass

getSilksOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getSilksResponse").pyclass

getSilksV2In = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getSilksV2").pyclass

getSilksV2Out = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "getSilksV2Response").pyclass

heartbeatIn = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "heartbeat").pyclass

heartbeatOut = GED("http://www.betfair.com/publicapi/v5/BFExchangeService/", "heartbeatResponse").pyclass


# Service Skeletons
class BFExchangeService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/BFExchangeService', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getAccountFunds(self, ps, **kw):
        request = ps.Parse(getAccountFundsIn.typecode)
        response = betfair_api.getAccountFunds(self, ps, request, getAccountFundsOut())
        return request,response

    soapAction['getAccountFunds'] = 'soap_getAccountFunds'
    root[(getAccountFundsIn.typecode.nspname,getAccountFundsIn.typecode.pname)] = 'soap_getAccountFunds'

    def soap_placeBets(self, ps, **kw):
        request = ps.Parse(placeBetsIn.typecode)
        response = betfair_api.placeBets(self, ps, request, placeBetsOut())
        return request,response

    soapAction['placeBets'] = 'soap_placeBets'
    root[(placeBetsIn.typecode.nspname,placeBetsIn.typecode.pname)] = 'soap_placeBets'



#############################
#    NOT IMPLEMENTED YET    #
#############################

    def soap_cancelBets(self, ps, **kw):
        request = ps.Parse(cancelBetsIn.typecode)
        return request,cancelBetsOut()

    soapAction['cancelBets'] = 'soap_cancelBets'
    root[(cancelBetsIn.typecode.nspname,cancelBetsIn.typecode.pname)] = 'soap_cancelBets'

    def soap_cancelBetsByMarket(self, ps, **kw):
        request = ps.Parse(cancelBetsByMarketIn.typecode)
        return request,cancelBetsByMarketOut()

    soapAction['cancelBetsByMarket'] = 'soap_cancelBetsByMarket'
    root[(cancelBetsByMarketIn.typecode.nspname,cancelBetsByMarketIn.typecode.pname)] = 'soap_cancelBetsByMarket'

    def soap_updateBets(self, ps, **kw):
        request = ps.Parse(updateBetsIn.typecode)
        return request,updateBetsOut()

    soapAction['updateBets'] = 'soap_updateBets'
    root[(updateBetsIn.typecode.nspname,updateBetsIn.typecode.pname)] = 'soap_updateBets'

    def soap_getMarket(self, ps, **kw):
        request = ps.Parse(getMarketIn.typecode)
        return request,getMarketOut()

    soapAction['getMarket'] = 'soap_getMarket'
    root[(getMarketIn.typecode.nspname,getMarketIn.typecode.pname)] = 'soap_getMarket'

    def soap_getMarketInfo(self, ps, **kw):
        request = ps.Parse(getMarketInfoIn.typecode)
        return request,getMarketInfoOut()

    soapAction['getMarketInfo'] = 'soap_getMarketInfo'
    root[(getMarketInfoIn.typecode.nspname,getMarketInfoIn.typecode.pname)] = 'soap_getMarketInfo'

    def soap_getMarketPrices(self, ps, **kw):
        request = ps.Parse(getMarketPricesIn.typecode)
        return request,getMarketPricesOut()

    soapAction['getMarketPrices'] = 'soap_getMarketPrices'
    root[(getMarketPricesIn.typecode.nspname,getMarketPricesIn.typecode.pname)] = 'soap_getMarketPrices'

    def soap_getCompleteMarketPricesCompressed(self, ps, **kw):
        request = ps.Parse(getCompleteMarketPricesCompressedIn.typecode)
        return request,getCompleteMarketPricesCompressedOut()

    soapAction['getCompleteMarketPricesCompressed'] = 'soap_getCompleteMarketPricesCompressed'
    root[(getCompleteMarketPricesCompressedIn.typecode.nspname,getCompleteMarketPricesCompressedIn.typecode.pname)] = 'soap_getCompleteMarketPricesCompressed'

    def soap_getMarketTradedVolumeCompressed(self, ps, **kw):
        request = ps.Parse(getMarketTradedVolumeCompressedIn.typecode)
        return request,getMarketTradedVolumeCompressedOut()

    soapAction['getMarketTradedVolumeCompressed'] = 'soap_getMarketTradedVolumeCompressed'
    root[(getMarketTradedVolumeCompressedIn.typecode.nspname,getMarketTradedVolumeCompressedIn.typecode.pname)] = 'soap_getMarketTradedVolumeCompressed'

    def soap_getMarketPricesCompressed(self, ps, **kw):
        request = ps.Parse(getMarketPricesCompressedIn.typecode)
        return request,getMarketPricesCompressedOut()

    soapAction['getMarketPricesCompressed'] = 'soap_getMarketPricesCompressed'
    root[(getMarketPricesCompressedIn.typecode.nspname,getMarketPricesCompressedIn.typecode.pname)] = 'soap_getMarketPricesCompressed'

    def soap_getAllMarkets(self, ps, **kw):
        request = ps.Parse(getAllMarketsIn.typecode)
        return request,getAllMarketsOut()

    soapAction['getAllMarkets'] = 'soap_getAllMarkets'
    root[(getAllMarketsIn.typecode.nspname,getAllMarketsIn.typecode.pname)] = 'soap_getAllMarkets'

    def soap_getInPlayMarkets(self, ps, **kw):
        request = ps.Parse(getInPlayMarketsIn.typecode)
        return request,getInPlayMarketsOut()

    soapAction['getInPlayMarkets'] = 'soap_getInPlayMarkets'
    root[(getInPlayMarketsIn.typecode.nspname,getInPlayMarketsIn.typecode.pname)] = 'soap_getInPlayMarkets'

    def soap_getPrivateMarkets(self, ps, **kw):
        request = ps.Parse(getPrivateMarketsIn.typecode)
        return request,getPrivateMarketsOut()

    soapAction['getPrivateMarkets'] = 'soap_getPrivateMarkets'
    root[(getPrivateMarketsIn.typecode.nspname,getPrivateMarketsIn.typecode.pname)] = 'soap_getPrivateMarkets'

    def soap_getCurrentBets(self, ps, **kw):
        request = ps.Parse(getCurrentBetsIn.typecode)
        return request,getCurrentBetsOut()

    soapAction['getCurrentBets'] = 'soap_getCurrentBets'
    root[(getCurrentBetsIn.typecode.nspname,getCurrentBetsIn.typecode.pname)] = 'soap_getCurrentBets'

    def soap_getCoupon(self, ps, **kw):
        request = ps.Parse(getCouponIn.typecode)
        return request,getCouponOut()

    soapAction['getCoupon'] = 'soap_getCoupon'
    root[(getCouponIn.typecode.nspname,getCouponIn.typecode.pname)] = 'soap_getCoupon'

    def soap_getCurrentBetsLite(self, ps, **kw):
        request = ps.Parse(getCurrentBetsLiteIn.typecode)
        return request,getCurrentBetsLiteOut()

    soapAction['getCurrentBetsLite'] = 'soap_getCurrentBetsLite'
    root[(getCurrentBetsLiteIn.typecode.nspname,getCurrentBetsLiteIn.typecode.pname)] = 'soap_getCurrentBetsLite'

    def soap_getMUBets(self, ps, **kw):
        request = ps.Parse(getMUBetsIn.typecode)
        return request,getMUBetsOut()

    soapAction['getMUBets'] = 'soap_getMUBets'
    root[(getMUBetsIn.typecode.nspname,getMUBetsIn.typecode.pname)] = 'soap_getMUBets'

    def soap_getMUBetsLite(self, ps, **kw):
        request = ps.Parse(getMUBetsLiteIn.typecode)
        return request,getMUBetsLiteOut()

    soapAction['getMUBetsLite'] = 'soap_getMUBetsLite'
    root[(getMUBetsLiteIn.typecode.nspname,getMUBetsLiteIn.typecode.pname)] = 'soap_getMUBetsLite'

    def soap_getDetailAvailableMktDepth(self, ps, **kw):
        request = ps.Parse(getDetailAvailableMktDepthIn.typecode)
        return request,getDetailAvailableMktDepthOut()

    soapAction['getDetailAvailableMktDepth'] = 'soap_getDetailAvailableMktDepth'
    root[(getDetailAvailableMktDepthIn.typecode.nspname,getDetailAvailableMktDepthIn.typecode.pname)] = 'soap_getDetailAvailableMktDepth'

    def soap_getMarketTradedVolume(self, ps, **kw):
        request = ps.Parse(getMarketTradedVolumeIn.typecode)
        return request,getMarketTradedVolumeOut()

    soapAction['getMarketTradedVolume'] = 'soap_getMarketTradedVolume'
    root[(getMarketTradedVolumeIn.typecode.nspname,getMarketTradedVolumeIn.typecode.pname)] = 'soap_getMarketTradedVolume'

    def soap_getBetHistory(self, ps, **kw):
        request = ps.Parse(getBetHistoryIn.typecode)
        return request,getBetHistoryOut()

    soapAction['getBetHistory'] = 'soap_getBetHistory'
    root[(getBetHistoryIn.typecode.nspname,getBetHistoryIn.typecode.pname)] = 'soap_getBetHistory'

    def soap_getAccountStatement(self, ps, **kw):
        request = ps.Parse(getAccountStatementIn.typecode)
        return request,getAccountStatementOut()

    soapAction['getAccountStatement'] = 'soap_getAccountStatement'
    root[(getAccountStatementIn.typecode.nspname,getAccountStatementIn.typecode.pname)] = 'soap_getAccountStatement'

    def soap_getMarketProfitAndLoss(self, ps, **kw):
        request = ps.Parse(getMarketProfitAndLossIn.typecode)
        return request,getMarketProfitAndLossOut()

    soapAction['getMarketProfitAndLoss'] = 'soap_getMarketProfitAndLoss'
    root[(getMarketProfitAndLossIn.typecode.nspname,getMarketProfitAndLossIn.typecode.pname)] = 'soap_getMarketProfitAndLoss'

    def soap_getBet(self, ps, **kw):
        request = ps.Parse(getBetIn.typecode)
        return request,getBetOut()

    soapAction['getBet'] = 'soap_getBet'
    root[(getBetIn.typecode.nspname,getBetIn.typecode.pname)] = 'soap_getBet'

    def soap_getBetLite(self, ps, **kw):
        request = ps.Parse(getBetLiteIn.typecode)
        return request,getBetLiteOut()

    soapAction['getBetLite'] = 'soap_getBetLite'
    root[(getBetLiteIn.typecode.nspname,getBetLiteIn.typecode.pname)] = 'soap_getBetLite'

    def soap_getBetMatchesLite(self, ps, **kw):
        request = ps.Parse(getBetMatchesLiteIn.typecode)
        return request,getBetMatchesLiteOut()

    soapAction['getBetMatchesLite'] = 'soap_getBetMatchesLite'
    root[(getBetMatchesLiteIn.typecode.nspname,getBetMatchesLiteIn.typecode.pname)] = 'soap_getBetMatchesLite'

    def soap_getSilks(self, ps, **kw):
        request = ps.Parse(getSilksIn.typecode)
        return request,getSilksOut()

    soapAction['getSilks'] = 'soap_getSilks'
    root[(getSilksIn.typecode.nspname,getSilksIn.typecode.pname)] = 'soap_getSilks'

    def soap_getSilksV2(self, ps, **kw):
        request = ps.Parse(getSilksV2In.typecode)
        return request,getSilksV2Out()

    soapAction['getSilksV2'] = 'soap_getSilksV2'
    root[(getSilksV2In.typecode.nspname,getSilksV2In.typecode.pname)] = 'soap_getSilksV2'

    def soap_heartbeat(self, ps, **kw):
        request = ps.Parse(heartbeatIn.typecode)
        return request,heartbeatOut()

    soapAction['heartbeat'] = 'soap_heartbeat'
    root[(heartbeatIn.typecode.nspname,heartbeatIn.typecode.pname)] = 'soap_heartbeat'

